usdot-fhwa-stol/connectedvcs-tools

- README.md
- build.sh
In this PR:
- A build file is added to build the map tool locally
- Updated the Readme file build instructions to use the new file
[MAP-128](https://usdot-carma.atlassian.net/browse/MAP-128)
Currently, the build instructions included in the Readme file consists of steps that need to be run manually run. This motivated to create a build file.
This has been tested by running the build file and verified that the projects builds successfully
[MAP-128]: https://usdot-carma.atlassian.net/browse/MAP-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 128 - Added build file and updated Readme file

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .github/workflows/dockerhub.yml
In this PR
- Updated the dockerhub.yml to push images to dockerhub for release candidate images and release images
- Updated ci.yml file to run tests and run sonar scanner for develop, master and release candidate images
[MAP-126](https://usdot-carma.atlassian.net/browse/MAP-126)
Currently, the MAP tool CI processes does not support generating images for release candidate and release images. Also, the CI process do run tests and run sonar scanner for release candidate images. This motivated to update the CI processes.
[MAP-126]: https://usdot-carma.atlassian.net/browse/MAP-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 126 - Updated MAP Tool CI processes

- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/input/IntersectionInputData.java
In this PR:
- Added a fix when approach type is missing
[MAP-107](https://usdot-carma.atlassian.net/browse/MAP-107)
This has been tested by creating a local docker image and testing the MAP message in local MAP Tool.
[MAP-107]: https://usdot-carma.atlassian.net/browse/MAP-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 107 - Added a fix when approach type is missing

- root/index.html
In this PR
- Buttons and Hyperlinks to TIM and Message Validator are removed
[MAP-131](https://usdot-carma.atlassian.net/browse/MAP-131)
Currently, there is no compiler that can encode TIM messages and Message Validator takes to 404 not found. For this reason,  links to these pages needed to be removed from the landing page.
This has been tested by building a docker image locally.
[MAP-131]: https://usdot-carma.atlassian.net/browse/MAP-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Map 131 - Disable links for tim and message validator

- ATTRIBUTION.md
- Code_of_Conduct.md
- Contributing.md
- README.md
In this PR
- Added  Contribution, Attribution, Code of Conduct files
- Update README file with Contribution, Attribution, Code of Conduct, License, Support, and Contact details.
[MAP-107](https://usdot-carma.atlassian.net/browse/MAP-107)
As we are releasing the code, this motivated us to update the README file with more details. 
[MAP-107]: https://usdot-carma.atlassian.net/browse/MAP-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Map 107 -  Update readme with more details

- ATTRIBUTION.md
In this PR
- Fixed a typo in ATTRIBUTION.md
[MAP-107](https://usdot-carma.atlassian.net/browse/MAP-107)
[MAP-107]: https://usdot-carma.atlassian.net/browse/MAP-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 107 - Fixed a typo in ATTRIBUTION.md

- ATTRIBUTION.md
- Code_of_Conduct.md
- Contributing.md
- README.md
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/input/IntersectionInputData.java
- root/index.html
Merge the release/2.0.0 branch into the master branch as part of the release process. This merge should be tagged and then deployed on the new production website.
https://usdot-carma.atlassian.net/browse/MAP-132
> Merge release/2.0.0 branch into master

- docs/Release_notes.md
This pull request adds release notes of version 2.0.0 of the MAP Tool
> Add Maptool 2.0.0 release notes

- ATTRIBUTION.md
- Code_of_Conduct.md
- Contributing.md
- README.md
- docs/Release_notes.md
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/input/IntersectionInputData.java
- root/index.html
This PR will merge master branch into develop branch to sync back release 2.0.0 changes.
> Sync Develop with Master branch

- fedgov-cv-lib-asn1c/src/main/java/gov_usdot_cv_rgaencoder_Encoder.h
- fedgov-cv-lib-asn1c/src/main/java/rga_wrapper.c
In this PR
- Added files needed for the JNI wrapper 
- Added the methods to encode the RGA message inside the rgawrapper.c file
- Using the JNI wrapper (header and C file), generated the .so file
[MAP-144](https://usdot-carma.atlassian.net/browse/MAP-144)
[MAP-144]: https://usdot-carma.atlassian.net/browse/MAP-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 144 - Develop the JNI wrapper file for RGA in lib-asn1c package and generate .so file

- fedgov-cv-lib-asn1c/src/main/java/rga_wrapper.c
- fedgov-cv-lib-asn1c/src/main/java/wrapper.c
In this PR
- Obtained the approved 2024 J2735 ASN1 spec and generated header and C files
- Updated the MAP message JNI wrapper file to support the change in variable type
- Fixed code error in RGA JNI wrapper and recompiled with approved J2735 ASN1 spec
[MAP-180](https://usdot-carma.atlassian.net/browse/MAP-180)
To update J2735 from 2016 to latest release
This has been tested by making sure all the unit test cases are passed and manually checking the MAP tool for encoded messages.
[MAP-180]: https://usdot-carma.atlassian.net/browse/MAP-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 180 - Updated the libasn1c.so file with J2735 2024 version

- docs/Docker_Instructions.md
Added specific line for API Key addition in documentation.
> 	modified:   docs/Docker_Instructions.md

- fedgov-cv-lib-asn1c/src/main/java/gov_usdot_cv_rgaencoder_Encoder.h
- fedgov-cv-lib-asn1c/src/main/java/rga_wrapper.c
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/input/IntersectionInputData.java
- fedgov-cv-message-builder/src/test/java/gov/usdot/cv/msg/builder/IntersectionSituationDataBuilderTest.java
- fedgov-cv-message-builder/src/test/resources/samplerga.json
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/BaseLayer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/DDate.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/DDateTime.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/Encoder.java
- fedgov-cv-rgaencoder/src/test/java/gov/usdot/cv/rgaencoder/RGAEncodeTest.java
For this, create “fedgov-cv-rgaencoder” package with Java class files for base layer to support RGA standard (+unit test).
NA
https://usdot-carma.atlassian.net/browse/MAP-143?atlOrigin=eyJpIjoiNmE2NWRiYmMxYmViNDk0NWJiMmY2MmY1MGJiNTFjZDAiLCJwIjoiaiJ9
Map tool
Local integration testing
> RGA Encoder and JNI Wrapper

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-TIMcreator-webapp/src/main/webapp/index.html
- root/index.html
The team recently compared the 2016 and 2024 versions of the MAP message in J2735 and found no differences for the MAP definition.  This story will update the notes for MAP Tool to indicate compliance with the 2024 version.  
Update version number on home page (index.html).
Update version number on ISD create page and TIM create page 
The current MapTool notes still indicate it is using J2735 2016 version.
https://usdot-carma.atlassian.net/browse/MAP-127
NA
NA
> Update map tool notes to indicate compliance with J2735 2024 version

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/bing.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
Reverts usdot-fhwa-stol/connectedvcs-tools#37
Reverting this PR , to merge the fix into the hotfix instead
> Revert "Hotfix update session key"

- Dockerfile
Reverts usdot-fhwa-stol/connectedvcs-tools#41
> Revert "	modified:   Dockerfile"

- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/services/GoogleElevationsService.java
When there is error reported from google API calls, the map services proxy did not report the status in ERROR log but rather in INFO log. This PR is to update the check to ensure error response from google API call are reported in ERROR log statement.
NA
NA
> Update map services proxy error logs

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/bing.js
- fedgov-cv-map-services-proxy/README.md
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/contollers/BingMapServicesController.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/models/BingMapProperties.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/services/BingImageryServices.java
- fedgov-cv-map-services-proxy/src/main/resources/application.properties
- fedgov-cv-map-services-proxy/src/test/java/gov/usdot/cv/bingmap/BingMapServicesControllerTest.java
Store the Bing Map API key in the map services proxy resource properties file.
Update imagery metadata to use API key rather than sharing the session key generated by UI.
NA
NA
> Update backend imagery metadata API to use bing map API key and store the API key in different location

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
- private-resources/js/ISDcreator-webapp-keys.js
Added a try/catch statement for node missing elevation. This allows the user to navigate to the encoder, but not encode until the nodes missing elevation are corrected. Red alerts are presented to the user detailing which nodes (and their corresponding lanes) are missing elevation.
[MAP-218 ](https://usdot-carma.atlassian.net/jira/software/c/projects/CS/boards/34?selectedIssue=MAP-218)
When a user upload a child map with a geojson file (see the attached child map geojson) and there are missing node elevation in node lanes, the user cannot navigate to message encoder dialog by clicking the encoder button.
Even the above error is resolved, when a user tries to encode an incomplete MAP JSON data without nodeElevation, it would not be able to encode it successfully and result in “00” in …
> MAP 218: Missing Node Elevation Error

- docs/Release_notes.md
Update Release_notes.md with Security Hotfix changes
> Update Release_notes.md with Security Hotfix 2.0.1

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
TileAge displayed on the MAPTool ISD map is updated every time user zoom in/out, move around a map. This update incurs bing map API billable calls. It is observed that there are more than 1200 calls to this bing map API a day, which leave the team around 100 days before it exhausts all the free API usage with this free version bing map account.   
NA
https://usdot-carma.atlassian.net/browse/MAP-222
> Hotfix/maptool 2.0.2

- docs/Release_notes.md
> Hotfix/2.0.2 Release notes

- docs/Release_notes.md
> Update Hotfix/2.0.2 Release notes

- .github/workflows/ci.yml
Update GitHub Actions workflows with latest version of third party actions from external repositories to remove deprecation warnings .
[ARC-250](https://usdot-carma.atlassian.net/browse/ARC-250)
[ARC-250]: https://usdot-carma.atlassian.net/browse/ARC-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update GitHub Actions Third-Party Action Versions

- Dockerfile
- build.sh
- docs/Docker_Instructions.md
- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/main.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
- fedgov-cv-map-services-proxy/.gitignore
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/contollers/BingMapServicesController.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/models/BingImageryMetadata.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/models/BingMapProperties.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/bingmap/services/BingImageryServices.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/filters/IpAddressFilter.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/controllers/GoogleMapServicesController.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GoogleElevationResponse.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GoogleLocation.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GoogleMapProperties.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GooglePlacePrediction.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GooglePlaceSuggestionItem.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GooglePlaceSuggestions.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GoogleSearchTextResponse.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/models/GoogleText.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/services/GoogleElevationsService.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/services/GooglePlacesService.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/utils/ClientRequestInfoParser.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/utils/RequestComposer.java
- fedgov-cv-map-services-proxy/src/test/java/gov/usdot/cv/googlemap/GoogleMapServicesControllerTest.java
Update fedgov-cv-map-services-proxy backend service to provide autocomplete place search features. This features are to replace the frontend javascript autocomplete places search because the javascript implementation exposes the google API key. This goal of this change is to protect the google API key by moving the key setting to the backend.
There are no UI look and feel changes, and users have experience no changes to use this place search functionalities.
NA
[MAP-211](https://usdot-carma.atlassian.net/browse/MAP-211)
Local integration testing
[MAP-211]: https://usdot-carma.atlassian.net/browse/MAP-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move autocomplete place search function into backend services

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapTools.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
Undefined getUsername() function error thrown when add a verified point marker.
When trying to save a new parent map, RemoveChild() notfoundError thrown.
https://usdot-carma.atlassian.net/browse/MAP-224
> Test Case 01 issue: Thrown getUsername() and RemoveChild() errors when create/edit/save a new parent map

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapTools.js
When click save on a child map, it sometimes show a notification for permission to download multiple files. Once click Allow, the file save dialog populated again after you hit save button at the top of the dialog.
NA
https://usdot-carma.atlassian.net/browse/MAP-227
NA
> Test case 06: Occasionally saving child map dialog popup multiple times

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
Full RAID Testing:
A user must enter at least two integers separated by a dot. The first integer should only be a number 0-2. If the first integer is 0 or 1, the second integer cannot exceed 39. No number can exceed 2147483647.
- 2.123.2147483647: Error caught, "integer at position 3 cannot be greater than 2147483647"
- 2.2147483647. error uncaught
Conditional check should be fixed to check this case for the second integer.
N/A
N/A
Local deployment
- [ x ] Defect fix (non-breaking change that fixes an issue)
- [] I have added any new packages to the sonar-scanner.properties file
- [ x  ] I have updated the documentation accordingly.
-  [ x ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ x  ] I have added …
> fixed conditional

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/config.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/IntersectionSituationDataBuilder.java
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/input/IntersectionInputData.java
- fedgov-cv-message-builder/src/test/java/gov/usdot/cv/msg/builder/IntersectionSituationDataBuilderTest.java
- fedgov-cv-message-builder/src/test/resources/samplerga3.json
- fedgov-cv-rgaencoder/src/test/java/gov/usdot/cv/rgaencoder/RGAEncodeTest.java
In this PR, we hardcoded the major and minor version to be 1 as per the J2945/A ASN1 standard and updated the related files.
MAP-91
> MAP 91 - Updated the code to set major and minor version as 1

- root/index.html
In this PR
- Added a link to redirect message validator to legacy webapp tool.
- Added a note below TIM tool that it is disabled for security enhancements.
MAP-238
> Map 238 cleanup maptool links

- docs/Release_notes.md
> Map tool 2.1.0 Release notes

- fedgov-cv-lib-asn1c/src/main/java/gov_usdot_cv_rgaencoder_Encoder.h
- fedgov-cv-lib-asn1c/src/main/java/rga_wrapper.c
- fedgov-cv-mapencoder/src/main/java/gov/usdot/cv/mapencoder/NodeXY20b.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/ApproachGeometryLayer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/BaseLayer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/BicycleLaneGeometryLayer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/ComputedXYZNodeInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/CrosswalkLaneGeometryLayer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/DuplicateXYZNodeInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/Encoder.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/GeometryContainer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/IndividualApproachGeometryInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/IndividualXYZNodeGeometryInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/IndvBikeLaneGeometryInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/IndvCrosswalkLaneGeometryInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/IndvMtrVehLaneGeometryInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/LaneConstructorType.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/MotorVehicleLaneGeometryLayer.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/NodeXYZOffsetInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/NodeXYZOffsetValue.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/PhysicalXYZNodeInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/RGAData.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/WayPlanarGeometryInfo.java
- fedgov-cv-rgaencoder/src/main/java/gov/usdot/cv/rgaencoder/WayWidth.java
- fedgov-cv-rgaencoder/src/test/java/gov/usdot/cv/rgaencoder/RGAEncodeTest.java
In this PR
- Added Java Files that includes mandatory fields for Geometry Container
- Added JNI wrapper for Geometry Container
- Updated test case with all the scenarios for Geometry Container
MAP-151
This has been tested using the new decoder.
> MAP 151 - Add Java files and JNI wrapper for mandatory fields of Geometry Container

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
Add Time Restrictions to Lane Info in MAP JSON
- Added location is at the lane level
```
{
"mapData": {
"minuteOfTheYear": 94515,
"layerType": "intersectionData",
"intersectionGeometry": {
"referencePoint": {
"descriptiveIntersctionName": "E Adams St & Woodward Ave",
"intersectionID": "29180",
"msgCount": "34",
"masterLaneWidth": "366",
"referenceLat": 42.336975895283814,
"referenceLon": -83.05084666004934,
"referenceElevation": "148"
},
"referencePointChild": {},
"verifiedPoint": {
"verifiedMapLat": 42.336971929923955,
"verifiedMapLon": -83.050634765538,
"verifiedMapElevation": "148",
"verifiedSurveyedLat": "42.33725346984514",
"verifiedSurveyedLon": "-83.05066963425483",
"verifiedSurveyedElevation": "148"
},
"laneList": {
"approach": [
{
"approachType": "Egress",
"approachID": "02", …
```
> Add Time Restrictions to Lane Info in MAP JSON

- fedgov-cv-ISDcreator-webapp/pom.xml
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/api.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/features.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/files.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/interactions.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/latlon-vincenty.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map-event.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/parent-child-latest.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/style.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
NA
[MAP-255](https://usdot-carma.atlassian.net/browse/MAP-255)
Map provider migration
[MAP-255]: https://usdot-carma.atlassian.net/browse/MAP-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  Porting Features modification on a parent/child map to use new openlayers API

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/config.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/IntersectionSituationDataBuilder.java
- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/input/IntersectionInputData.java
- private-resources/js/ISDcreator-webapp-keys.js
Adding OffsetZ throughout HTML/JS in the frontend. Adding Elevation offset to JSON deposit. Lastly, implementing the offset within the java files.
N/A
MAP-265
Computed Lane logic in the UI supports only offsetX and offsetY as only these two are required for the MAP message. On the other hand, RGA requires NodeXOffset, NodeYOffset, and NodeZOffset values for a computed lane. For this, MAP Tool UI needs to be updated to support elevation offset for computed lanes.
Local Docker Builds
- [ x ] Defect fix (non-breaking change that fixes an issue)
- [ x ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
> elevation calculation

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/main.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
In this PR
- Fixed time restrictions object in MAP JSON to support message builder intersectioninput.java file
- Fixed lane time restrictions to be enabled  or disabled when RGA button is enabled or disabled 
- Fixed a big where RGA fields were greyed out on first load even when RGA button is enabled
- Fixed  days of the week (weekday) options being greyed out while selecting time restrictions for second lane after selection ALL for first lane
[MAP-275](https://usdot-carma.atlassian.net/browse/MAP-275)
[MAP-275]: https://usdot-carma.atlassian.net/browse/MAP-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Map 275 - Bug fixes to time restrictions from RGA geometry container integration testing 

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
In this PR
- Fixed a bug from time restrictions while drawing a computed lane
MAP-275
> MAP 275 - Fixed a bug in time restrictions while drawing computed lane

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/features.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/style.js
These changes are to address issues found during local integration testing.
- Fix clicking on overlapping features and their interactions.
- Add missing clear Map functionality
- Change lane markers, approach, and lane number display style
- Fix computed lane index and lane number mismatch
- Update layers zIndex to allow consistent features display 
- Fix sharedWith for computed lane
NA
[MAP-261](https://usdot-carma.atlassian.net/browse/MAP-261)
Map provider migration 
Local integration testing
[MAP-261]: https://usdot-carma.atlassian.net/browse/MAP-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix map provider migration

- fedgov-cv-message-builder/src/main/java/gov/usdot/cv/msg/builder/IntersectionSituationDataBuilder.java
- fedgov-cv-message-builder/src/test/java/gov/usdot/cv/msg/builder/IntersectionSituationDataBuilderTest.java
- fedgov-cv-message-builder/src/test/resources/samplerga10.json
In this PR
- Fixed time restrictions bug in message builder
MAP-275
> MAP 275 - Fixed time restrictions bug in message builder

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
In this PR
- Fixed bug that would remove empty speed limit types being added to MAP JSON
[MAP-285](https://usdot-carma.atlassian.net/browse/MAP-285)
[MAP-285]: https://usdot-carma.atlassian.net/browse/MAP-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 285 - Fixed speed limits bug on MAP Tool UI

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
Updated the instructions on the MAP UI to include RGA specific instructions. Only contains instructions for the base map and geometry container changes.
[MAP-166](https://usdot-carma.atlassian.net/jira/software/c/projects/CS/boards/34?selectedIssue=MAP-166)
Allows the user to view instructions for creating an RGA message.
https://leidoscorpus.sharepoint.us/:w:/r/sites/STR/TODevelopmentLibrary/22-268%20MAP%20Tool%20Update/Work-In-Progress/Testing/2025%20March/About%20Page%20Screenshots.docx?d=wcdcbab573c8b4024b706d8e588ed787c&csf=1&web=1&e=1pqkx1
- [x ] New feature (non-breaking change that adds functionality)
[MAP-166]: https://usdot-carma.atlassian.net/browse/MAP-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated instructions to include rga specific

- fedgov-cv-ISDcreator-webapp/README.md
- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/mapping.js
- root/index.html
In this PR, updated MAP Tool with the following changes
- Removed SPAT warning messages
- Hidden SPAT tab from Lane Configuration
- Hidden SPAT related message types
- Removed ISD references
[MAP-245](https://usdot-carma.atlassian.net/browse/MAP-245)
This has been tested by deploying locally and testing it
[MAP-245]: https://usdot-carma.atlassian.net/browse/MAP-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 245 - Removed SPAT and ISD references from MAP Tool

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/interactions.js
Connection arrows are not implemented with the new base map
[MAP-292](https://usdot-carma.atlassian.net/browse/MAP-292)
[MAP-292]: https://usdot-carma.atlassian.net/browse/MAP-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix: Connection arrows are not implemented with the new base map

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
Fixed a bug that did not store None option for time restrictions
MAP-293
> MAP 293 - Fixed time restrictions bug

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
When click on the reference point marker and update any  fields other than revision number, the revision number is reset to 0. This PR is to remove the logic to update the revision number as it is disabled in the UI and should be viewable only.
NA
NA
> Fix: Revision number was reset to 0

- fedgov-cv-message-builder/pom.xml
Fixed surefire plugin configuration to fix failing local build
MAP-291
> Fixed broken build in local

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/api.js
In this PR
- Fixed migration of intersection url
MAP-300
> Map 300 -  Fix migration of intersection url

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
In this, fixed warning messages that does not appear for the Sidewalk and Parking lanes when message type is RGA
MAP-300
> Map 301 fix warning messages for rga

- docs/Release_notes.md
In this PR
- Added release notes for the release 2.2.0
[MAP-268](https://usdot-carma.atlassian.net/browse/MAP-268)
[MAP-268]: https://usdot-carma.atlassian.net/browse/MAP-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Release_notes.md for Map tool 2.2.0

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
> Added release version to maptool ui

- docs/Release_notes.md
- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
> Hotfix fix release version in UI 2.2.1

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
If an approach is added accidentally, encoder pop up does not open instead of giving an error to the user that an empty approach has been added. A map file is added below to replicate the issue.
[MAP-287](https://usdot-carma.atlassian.net/browse/MAP-287)
Local Integration Test
[MAP-287]: https://usdot-carma.atlassian.net/browse/MAP-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 287 - Unable to open encoder pop up if an approach is added accidentally with no approach ID

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/config.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
NA
[MAP-303](https://usdot-carma.atlassian.net/browse/MAP-303)
UI support for Wayuse Container to RGA Message
- RGA Disabled (No options selected):
- RGA enabled (No options selected)
[MAP-303]: https://usdot-carma.atlassian.net/browse/MAP-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 303 - Add RGA fields for speed limits at lane level

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
In this PR
- Added logic to show warnings when right u-turn lane attribute is added for both MAP and RGA encodings
- Added logic to show warnings that Lane Change Allowed and No stopping maneuvers are supported in RGA yet 
MAP-308
Figure 1: Lane Configuration Window on the right shows Connections from Lane 4 
Figure 2: Lane Configuration Window on the right shows Lane Attributes for Lane 1
Figure 3: Lane Configuration Window on the right shows Lane Attributes for Lane 2
> MAP 308 - Added logic to show maneuver warnings for both RGA and MAP

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
If a right u-turn is added and RGA is disabled, a warning message should be added even though the maneuver gets removed in the logic of the depositor. A warning message is added so that the user knows that the maneuver is unsupported.
[MAP-329](https://usdot-carma.atlassian.net/browse/MAP-329)
Fixes bug found from Maneuver Container testing
Tested locally
- [ x] Defect fix (non-breaking change that fixes an issue)
- [x ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
[MAP-329]: https://usdot-carma.atlassian.net/browse/MAP-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated depositor to fix right uturn bugfix

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
Added appropriate tags and disabling of the speed limit time period configurations (general and range). 
MAP-335
When RGA is disabled, time restrictions should be disabled. This means greyed out and not editable. Currently, parts of the Speed Limit time restrictions, when the time period is set to general or range, are not being disabled.
Local Docker Deployment Testing
> fixed disabling of general and range time period configs

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
Created hotfix for the bugfix in MAP-330. This hotfix fixes a bug identified by users when a maneuver is deleted in either the lane attributes or the lane connections table. Furthermore, this hotfix allows for already saved maneuvers in the lane connections table to be deleted, when before, it was unable to be deleted when the maneuvers are saved.
[MAP-338](https://usdot-carma.atlassian.net/jira/software/c/projects/MAP/boards/48/backlog?selectedIssue=MAP-338)
Bugfix: [MAP-330](https://usdot-carma.atlassian.net/jira/software/c/projects/MAP/boards/48/backlog?selectedIssue=MAP-330)
Hotfix to fix bugs presented in previous release with deleting maneuvers
Local testing
- [ x] Defect fix (non-breaking change that fixes an issue)
- [ x] I have read the …
> Made changes to hotfix branch to fix deletion of maneuvers bug

- docs/Release_notes.md
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
This PR is to Merge hotfix changes hotfix branch back into master as part of release process for version maptool-2.2.2
> Merge hotfix release to master for maptool-2.2.2

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
This PR is to Fix release version of the MAP tool UI when clicked on About button under the Help Menu.
> Hotfix fix release version in UI 2.2.2

- fedgov-cv-ISDcreator-webapp/src/main/webapp/external/bootstrap/css/bootstrap.css
- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
Added alert to the Encoder panel that tells the user RGA data (Content Version, Content Date Time, and/or Mapped Geometry ID) is missing from the Reference Point Marker.
MAP-337
When loading an old MAP file and navigating to the encoder an error appears in the console due to no RGA data being filed. Because of this, the encoder pop up fails to load in and nothing happens. Figure out a way to open the encoder without have the rga data present. Specifically, the content date time missing is what causes the error.
Local Docker Deployment
> warning message for missing rga data in RPM

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-map-services-proxy/pom.xml
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/azuremap/controllers/TileProxyController.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/config/ProjectConfig.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/filters/RefererFilter.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/googlemap/controllers/GoogleMapServicesController.java
- fedgov-cv-map-services-proxy/src/main/java/gov/usdot/cv/security/CSRFTokenController.java
- fedgov-cv-map-services-proxy/src/main/resources/application.properties
- fedgov-cv-map-services-proxy/src/test/java/gov/usdot/cv/azuremap/TileProxyControllerTest.java
- fedgov-cv-map-services-proxy/src/test/java/gov/usdot/cv/filters/RefererFilterTest.java
- Add Cross Site Request Forgery restrictions to Tileset API
- Add Referer Header filters to all API request
NA
[MAP-342](https://usdot-carma.atlassian.net/browse/MAP-342)
NA
Local Integration Test
[MAP-342]: https://usdot-carma.atlassian.net/browse/MAP-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Cross Site Request Forgery and  Referer headers protection to tileset API

- root/index.html
In this PR
- Updated TIM Tool text
MAP-351
> MAP 351 - Updated TIM Tool text

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/row.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/time-restrictions.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
In this PR
- Fixed an issue in the deleteRow() and changeRow() methods while deleting a row in Approaches Table
- Fixed an issue in the saveConnections() method while saving the data from table into the approaches object
- Updated connection row id values to make them unique
[MAP-354](https://usdot-carma.atlassian.net/browse/MAP-354)
[MAP-354]: https://usdot-carma.atlassian.net/browse/MAP-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 354 - Fixed Lane Connections Configuration Table

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/row.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
In this PR
Fixed an issue in the deleteRow() and changeRow() methods while deleting a row in Approaches Table
Fixed an issue in the saveConnections() method while saving the data from table into the approaches object
Updated connection row id values to make them unique
[MAP-354](https://usdot-carma.atlassian.net/browse/MAP-354)
[MAP-354]: https://usdot-carma.atlassian.net/browse/MAP-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP 354 - Fixed Lane Connections Bug while deleting them

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
Reverts usdot-fhwa-stol/connectedvcs-tools#179
> Revert "MAP 356 - Fixed Right U-turn to be draggable"

- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/row.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/time-restrictions.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
Reverts usdot-fhwa-stol/connectedvcs-tools#180
> Revert "MAP 354 - Fixed Lane Connections Configuration Table"

- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/depositor-latest.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/map.js
- fedgov-cv-ISDcreator-webapp/src/main/webapp/js/utils.js
Changed placeholder text and added error for revision number input. Added error alert in the encoder when the revision number is greater than 127.
MAP-357
Revision Numbers greater than 127 return a null pointer exception in the encoder.
Local Docker Deployment Testing
> MAP 357 - fixed revision number input

- docs/Release_notes.md
- fedgov-cv-ISDcreator-webapp/src/main/webapp/index.html
This PR Added release notes for the release 2.3.0
[MAP-322](https://usdot-carma.atlassian.net/browse/MAP-322)
[MAP-322]: https://usdot-carma.atlassian.net/browse/MAP-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Release_notes.md for Map tool 2.3.0

- docs/Release_notes.md
This PR is to address comments on releasenotes page for 2.3.0 release
> Update Releasenotes.md for 2.3.0 release
